# Site settings
title: 汀汀涔涔
name: 汀汀涔涔
email: ttccmvp@gmail.com
location: Chengdu, Sichuang
github_url: https://github.com/imwr
weibo_url: https://weibo.com/imwr
description: 汀汀涔涔 Personal Website of TTCC
url: http://tt-cc.cn

# About/contact
author:
  contact:
    github:    https://github.com/imwr
    weibo:     http://weibo.com/imwr
    email:     ttccmvp@gmail.com

# Plugins
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
  - kramdown
  - jekyll-github-metadata

# Where things are
collections:
  my_categories:
    output: true
    permalink: /categories/:name/
  my_tags:
    output: true
    permalink: /tags/:name/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tag

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /tags
    label: Tags

  -
    href: /categories
    label: Categories

# Pagination
permalink: /:categories/:title/
paginate: 5
paginate_path: "/blog/page:num/"

# Where are tags and categories displayed
tag_page: tags
category_page: categories

# github metadata
repository: imwr/imwr.github.com

# kramdown
kramdown:
  input: GFM
  syntax_highlighter: true

# Sidebar to show popular repo
side_bar_repo_limit: 5

# Disque
disque: tt-cc.disqus.com
# Google Analytics
google_tracking_id : 'UA-79713062-1'

# For about.html. Fell free to create your own!
skill_software_keywords: [Java, Objective C, MySQL, MongoDB, SSDB, Redis，Lua]
skill_j2ee_keywords: [SpringMvc, Struct, MyBatis, Velocity]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, Boostrap]

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, node_modules]


#test
easydebug:
github-test:
  public_repositories:
    -
      name: fa2png.io - v21
      stargazers_count: 0
      forks_count: 22
      updated_at: 2015-12-12
      stargazers_count: 1
      description: 这是是一个啦减肥啦手机发的啦快速减肥卢卡斯地方
      fork: false
    -
      name: fa2png.io - v22
      stargazers_count: 0
      forks_count: 22
      updated_at: 2015-12-12
      stargazers_count: 1
      description: 这是是一个啦减肥啦手机发的啦快速减肥卢卡斯地方
      fork: false
    -
      name: fa2png.io - v23
      stargazers_count: 0
      forks_count: 22
      updated_at: 2015-12-12
      stargazers_count: 1
      description: 这是是一个啦减肥啦手机发的啦快速减肥卢卡斯地
      fork: false