# Site settings
title: 汀汀涔涔
name: 汀汀涔涔
email: ttccmvp@gmail.com
location: Chengdu, Sichuang
company: DM
github_url: https://github.com/imwr
description: This is personnel website of ttcc
# url: http://tt-cc.cn
url: http://localhost:4000

# About/contact
author:
  contact:
    github:    https://github.com/imwr
    weibo:     http://weibo.com/imwr
    email:     ttccmvp@gmail.com

source:      .
destination: ./_site

quiet:    false
defaults: []

# Plugins
gems:
  - jekyll-seo-tag

# Pagination
permalink: /:categories/:title/
paginate: 10
paginate_path: "/blog/page:num/"

# Where are tags and categories displayed
tag_page: '/tags'
category_page: '/categories'

# lunr search
lunr_search:
  js_dir: "components/search-jekyll"
  stopwords: ''
  min_length: 3

# github metadata
repository: imwr/imwr.github.com

# tagging
tag_page_layout: tagpage
tag_page_dir: tag
tag_permalink_style: pretty

# category_archive
category_archive:
  slugify: true
  path: category

# press
jekyll-press:
  exclude: 'index.xml' # Exclude files from processing
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /tags
    label: Tags

  -
    href: /categories
    label: Categories

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5

# Disque
disque: tt-cc.disqus.com
# Google Analytics
google_tracking_id : 'UA-79713062-1'


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]